### PR TITLE
Add a new surface tension model

### PR DESCRIPTION
**Pull request by gileoo**
This is a cleaned-up version of the original code from 
https://www.mdpi.com/2073-431X/9/2/23

However, it is has some different behavior, from the splishsplash version I was  working on during the paper production. (some months ago). It will need some additional work/fixes.

I also added the test scenes. (I can move them to the supplementary material repo, if it becomes too much here)

I added three color maps, which help to investigate fields located around the origin. Blue-White-Red (also with an atan scale) and Blue-White-Green.

### CODE REVIEW

**Comment by gileoo** [comment]
Ok. It should be ready to go now.

**Comment by janbender** [comment]
Some comments to the scene files:

In different scenes you use WCSPH. However, this method is an explicit one and only conditionally stable. E.g. in the crown scene many particles go through the boundary. To avoid such artifacts I recommend to use an implicit scheme. Currently, DFSPH is the fastest solver. You could even increase the max error to decrease the number of iterations. 

For some scenes you should set the "isWall" parameter to false for some rigid bodies. E.g. in SurfaceTension_CoveredSphere_ZR2020 the sphere would then be visible. The parameter just defines which bodies are visible/invisible by default. 

Currently, our default boundary handling method is "boundaryHandlingMethod": 2. Maybe you want to try this one.

In the scene SurfaceTension_DoubleDroplet_ZR2020, SurfaceTension_NoGravCube_ZR2020 and SurfaceTension_SnakeTestZR2020 you use PCISPH. I would not recommend this pressure solver since it is less stable and converges slowly.

The scene SurfaceTension_FilledSaddle_ZR2020 does not work well for me. First, I would recommend to use the CFL condition. Second, something is wrong with the saddle.obj. The simulator complains that the mesh is not closed and the visualization also has problems.

**Comment by gileoo** [comment]
Thank you for the feedback.
I'll improve the scenes. For the saddle experiment I actually, had a feature implemented, that adjust viscosity after some time steps; such that it converges faster to a steady state with the fluid at almost rest. I'll fix the obj.

I actually had some troubles with the boundary method 2, especially in the BoxHole scene.

**Comment by gileoo** [comment]
Code and scenes are updated.

**Pull request closed without merging**
